version: "3.9"
services:
  www:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx/config.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    image: php:fpm
    volumes:
      - ./:/var/www/html/
    links:
      - database
      - maildev

  database:
    image: library/mariadb:10.5.8
    ports:
      [ 3306 ]
    volumes:
      - ./docker/db/data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inscriptions

  phpmyadmin:
    environment: [PMA_HOST=database, PMA_USER=root, PMA_PASSWORD=rootpassword, PHP_UPLOAD_MAX_FILESIZE=100MB]
    expose: [ 80 ]
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    links:
      - database
    ports:
      - 8080:80
  maildev:
    image: schickling/mailcatcher
    ports: [1025, 1080]
